# Generated by Django 5.1.1 on 2024-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('id_number', models.PositiveIntegerField(null=True)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField(default=0)),
                ('residence', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('visit_date', models.DateField()),
                ('specialist', models.CharField(max_length=100, null=True)),
                ('doctor_number', models.PositiveIntegerField(null=True)),
                ('medical_diagnosis', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
