# Generated by Django 5.1.1 on 2024-10-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='record',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
